name: Doompedia
options:
  deploymentTarget:
    iOS: 17.0
  createIntermediateGroups: true

targets:
  Doompedia:
    type: application
    platform: iOS
    sources:
      - Doompedia
    resources:
      - Doompedia/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.feelbachelor.doompedia.ios
        PRODUCT_NAME: Doompedia
        SWIFT_VERSION: 5.9
        INFOPLIST_KEY_CFBundleDisplayName: Doompedia
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.reference
        GENERATE_INFOPLIST_FILE: YES

  DoompediaTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - DoompediaTests
    dependencies:
      - target: Doompedia
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.feelbachelor.doompedia.ios.tests
